# Generated by Django 4.2.4 on 2023-08-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
